// Code generated by protoc-gen-go. DO NOT EDIT.
// source: task.proto

package task

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	job "github.com/scaumiao/autotest/proto/job"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// message CreateTaskRequest {
//     string name = 1;
// }
// message CreateTaskResponse {
//     string id = 1;
// }
// message UpdateTaskRequest {
//     string id = 1;
//     string name = 2;
// }
type Task struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Script               string   `protobuf:"bytes,3,opt,name=script,proto3" json:"script,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Task) Reset()         { *m = Task{} }
func (m *Task) String() string { return proto.CompactTextString(m) }
func (*Task) ProtoMessage()    {}
func (*Task) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce5d8dd45b4a91ff, []int{0}
}

func (m *Task) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Task.Unmarshal(m, b)
}
func (m *Task) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Task.Marshal(b, m, deterministic)
}
func (m *Task) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Task.Merge(m, src)
}
func (m *Task) XXX_Size() int {
	return xxx_messageInfo_Task.Size(m)
}
func (m *Task) XXX_DiscardUnknown() {
	xxx_messageInfo_Task.DiscardUnknown(m)
}

var xxx_messageInfo_Task proto.InternalMessageInfo

func (m *Task) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Task) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Task) GetScript() string {
	if m != nil {
		return m.Script
	}
	return ""
}

type TaskList struct {
	Tasks                []*Task  `protobuf:"bytes,1,rep,name=tasks,proto3" json:"tasks,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TaskList) Reset()         { *m = TaskList{} }
func (m *TaskList) String() string { return proto.CompactTextString(m) }
func (*TaskList) ProtoMessage()    {}
func (*TaskList) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce5d8dd45b4a91ff, []int{1}
}

func (m *TaskList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TaskList.Unmarshal(m, b)
}
func (m *TaskList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TaskList.Marshal(b, m, deterministic)
}
func (m *TaskList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TaskList.Merge(m, src)
}
func (m *TaskList) XXX_Size() int {
	return xxx_messageInfo_TaskList.Size(m)
}
func (m *TaskList) XXX_DiscardUnknown() {
	xxx_messageInfo_TaskList.DiscardUnknown(m)
}

var xxx_messageInfo_TaskList proto.InternalMessageInfo

func (m *TaskList) GetTasks() []*Task {
	if m != nil {
		return m.Tasks
	}
	return nil
}

func init() {
	proto.RegisterType((*Task)(nil), "autotest.protobuf.Task")
	proto.RegisterType((*TaskList)(nil), "autotest.protobuf.TaskList")
}

func init() { proto.RegisterFile("task.proto", fileDescriptor_ce5d8dd45b4a91ff) }

var fileDescriptor_ce5d8dd45b4a91ff = []byte{
	// 390 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x92, 0xcb, 0x6a, 0xdb, 0x40,
	0x14, 0x86, 0x91, 0xec, 0xfa, 0x72, 0x84, 0x5b, 0x3c, 0xa6, 0xaa, 0x90, 0xbd, 0x30, 0x5a, 0x19,
	0xd3, 0x6a, 0xa8, 0xbb, 0xaa, 0xbb, 0x73, 0x5b, 0x0a, 0xa5, 0x2b, 0xb9, 0x06, 0xd3, 0xdd, 0x48,
	0x9a, 0x3a, 0x13, 0x5b, 0x1a, 0xa1, 0x19, 0x19, 0x42, 0xc8, 0x26, 0xaf, 0x90, 0x4d, 0xde, 0x2b,
	0xaf, 0x90, 0x07, 0x09, 0x33, 0x92, 0x08, 0x4e, 0xe2, 0x2c, 0xbc, 0xd0, 0xe5, 0xdc, 0xbe, 0x39,
	0xff, 0xcf, 0x00, 0x48, 0x22, 0xb6, 0x7e, 0x96, 0x73, 0xc9, 0x51, 0x9f, 0x14, 0x92, 0x4b, 0x2a,
	0x64, 0x19, 0x87, 0xc5, 0x7f, 0x77, 0xb4, 0xe1, 0x7c, 0xb3, 0xa3, 0x98, 0x64, 0x0c, 0x93, 0x34,
	0xe5, 0x92, 0x48, 0xc6, 0x53, 0x51, 0x36, 0xb8, 0xc3, 0xaa, 0x5a, 0xb7, 0x63, 0x9a, 0x64, 0xf2,
	0xa2, 0x2a, 0x0e, 0xf4, 0x07, 0x9f, 0xf3, 0x50, 0x3d, 0x65, 0xd2, 0x5b, 0x40, 0xf3, 0x2f, 0x11,
	0x5b, 0xf4, 0x16, 0x4c, 0x16, 0x3b, 0xc6, 0xd8, 0x98, 0x74, 0x03, 0x93, 0xc5, 0x08, 0x41, 0x33,
	0x25, 0x09, 0x75, 0x4c, 0x9d, 0xd1, 0xff, 0xc8, 0x86, 0x96, 0x88, 0x72, 0x96, 0x49, 0xa7, 0xa1,
	0xb3, 0x55, 0xe4, 0x7d, 0x85, 0x8e, 0x62, 0xfc, 0x61, 0x42, 0xa2, 0x4f, 0xf0, 0x46, 0x09, 0x10,
	0x8e, 0x31, 0x6e, 0x4c, 0xac, 0xd9, 0x07, 0xff, 0x99, 0x04, 0x5f, 0xf5, 0x06, 0x65, 0xd7, 0xec,
	0xb6, 0x09, 0x96, 0x8a, 0x97, 0x34, 0xdf, 0xb3, 0x88, 0xa2, 0x25, 0xc0, 0xf7, 0x9c, 0x12, 0x49,
	0xf5, 0x52, 0xc7, 0xa6, 0xdd, 0x63, 0x05, 0x6f, 0x70, 0x7d, 0x77, 0x7f, 0x63, 0xf6, 0xbc, 0x0e,
	0xde, 0x7f, 0xc6, 0xea, 0x88, 0xb9, 0x31, 0x45, 0x01, 0xb4, 0x7f, 0x51, 0x79, 0x22, 0xf1, 0xbd,
	0x26, 0xbe, 0x43, 0xbd, 0x9a, 0x88, 0x2f, 0x59, 0x7c, 0x85, 0x56, 0x60, 0x55, 0x4c, 0x2d, 0xdb,
	0xf6, 0x4b, 0xe7, 0x1f, 0x87, 0x7f, 0x2a, 0xe7, 0xdd, 0xe1, 0x11, 0xac, 0x1a, 0xf2, 0xfa, 0x1a,
	0x6d, 0xa1, 0x6e, 0x8d, 0x16, 0x68, 0x05, 0xf0, 0x83, 0xee, 0xe8, 0xc9, 0xfa, 0xab, 0x6d, 0xa7,
	0x4f, 0xb6, 0x5d, 0x03, 0xac, 0xb2, 0xf8, 0x74, 0x5b, 0x1d, 0x8d, 0x45, 0xee, 0x21, 0x56, 0x79,
	0xbb, 0x86, 0x76, 0x50, 0xa4, 0xaf, 0x63, 0xed, 0x17, 0x0a, 0xbf, 0x79, 0xe8, 0x8d, 0x34, 0xd5,
	0xf6, 0xfa, 0x07, 0x54, 0x9c, 0x17, 0xe9, 0xdc, 0x98, 0x2e, 0xfc, 0x7f, 0x1f, 0x37, 0x4c, 0x9e,
	0x15, 0xa1, 0x1f, 0xf1, 0x04, 0x8b, 0x88, 0x14, 0x09, 0x23, 0x1c, 0xd7, 0xa8, 0xf2, 0x8e, 0xeb,
	0xb1, 0x6f, 0xea, 0x15, 0xb6, 0x74, 0xe2, 0xcb, 0x43, 0x00, 0x00, 0x00, 0xff, 0xff, 0x86, 0xc2,
	0x2f, 0x99, 0x41, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// TaskServiceClient is the client API for TaskService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TaskServiceClient interface {
	CreateTask(ctx context.Context, in *Task, opts ...grpc.CallOption) (*Task, error)
	GetTask(ctx context.Context, in *Task, opts ...grpc.CallOption) (*Task, error)
	GetTaskList(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*TaskList, error)
	DeleteTask(ctx context.Context, in *Task, opts ...grpc.CallOption) (*Task, error)
	UpdateTask(ctx context.Context, in *Task, opts ...grpc.CallOption) (*Task, error)
	RunTask(ctx context.Context, in *Task, opts ...grpc.CallOption) (*job.Job, error)
}

type taskServiceClient struct {
	cc *grpc.ClientConn
}

func NewTaskServiceClient(cc *grpc.ClientConn) TaskServiceClient {
	return &taskServiceClient{cc}
}

func (c *taskServiceClient) CreateTask(ctx context.Context, in *Task, opts ...grpc.CallOption) (*Task, error) {
	out := new(Task)
	err := c.cc.Invoke(ctx, "/autotest.protobuf.TaskService/CreateTask", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskServiceClient) GetTask(ctx context.Context, in *Task, opts ...grpc.CallOption) (*Task, error) {
	out := new(Task)
	err := c.cc.Invoke(ctx, "/autotest.protobuf.TaskService/GetTask", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskServiceClient) GetTaskList(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*TaskList, error) {
	out := new(TaskList)
	err := c.cc.Invoke(ctx, "/autotest.protobuf.TaskService/GetTaskList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskServiceClient) DeleteTask(ctx context.Context, in *Task, opts ...grpc.CallOption) (*Task, error) {
	out := new(Task)
	err := c.cc.Invoke(ctx, "/autotest.protobuf.TaskService/DeleteTask", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskServiceClient) UpdateTask(ctx context.Context, in *Task, opts ...grpc.CallOption) (*Task, error) {
	out := new(Task)
	err := c.cc.Invoke(ctx, "/autotest.protobuf.TaskService/UpdateTask", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskServiceClient) RunTask(ctx context.Context, in *Task, opts ...grpc.CallOption) (*job.Job, error) {
	out := new(job.Job)
	err := c.cc.Invoke(ctx, "/autotest.protobuf.TaskService/RunTask", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TaskServiceServer is the server API for TaskService service.
type TaskServiceServer interface {
	CreateTask(context.Context, *Task) (*Task, error)
	GetTask(context.Context, *Task) (*Task, error)
	GetTaskList(context.Context, *empty.Empty) (*TaskList, error)
	DeleteTask(context.Context, *Task) (*Task, error)
	UpdateTask(context.Context, *Task) (*Task, error)
	RunTask(context.Context, *Task) (*job.Job, error)
}

func RegisterTaskServiceServer(s *grpc.Server, srv TaskServiceServer) {
	s.RegisterService(&_TaskService_serviceDesc, srv)
}

func _TaskService_CreateTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Task)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServiceServer).CreateTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/autotest.protobuf.TaskService/CreateTask",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceServer).CreateTask(ctx, req.(*Task))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskService_GetTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Task)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServiceServer).GetTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/autotest.protobuf.TaskService/GetTask",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceServer).GetTask(ctx, req.(*Task))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskService_GetTaskList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServiceServer).GetTaskList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/autotest.protobuf.TaskService/GetTaskList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceServer).GetTaskList(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskService_DeleteTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Task)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServiceServer).DeleteTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/autotest.protobuf.TaskService/DeleteTask",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceServer).DeleteTask(ctx, req.(*Task))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskService_UpdateTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Task)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServiceServer).UpdateTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/autotest.protobuf.TaskService/UpdateTask",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceServer).UpdateTask(ctx, req.(*Task))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskService_RunTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Task)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServiceServer).RunTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/autotest.protobuf.TaskService/RunTask",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceServer).RunTask(ctx, req.(*Task))
	}
	return interceptor(ctx, in, info, handler)
}

var _TaskService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "autotest.protobuf.TaskService",
	HandlerType: (*TaskServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateTask",
			Handler:    _TaskService_CreateTask_Handler,
		},
		{
			MethodName: "GetTask",
			Handler:    _TaskService_GetTask_Handler,
		},
		{
			MethodName: "GetTaskList",
			Handler:    _TaskService_GetTaskList_Handler,
		},
		{
			MethodName: "DeleteTask",
			Handler:    _TaskService_DeleteTask_Handler,
		},
		{
			MethodName: "UpdateTask",
			Handler:    _TaskService_UpdateTask_Handler,
		},
		{
			MethodName: "RunTask",
			Handler:    _TaskService_RunTask_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "task.proto",
}
